from __future__ import annotations

import json
import os
import re
import shutil
import time

from . import dock, pipeline, render, upstream
from .extract import Finding, load
from .versions import NIGHTLY_VERSION, by_key, matrix, order

BUNDLES = "bundles"


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")[:60]


EXPECTED_BY_KIND = {
    "WRONG_RESULT": "The distributed result equals the single-process (plain tensor) result on every rank.",
    "OOB_WRITE": "The backend writes only inside the tensor it was given.",
    "HANG": "The op returns (the equivalent plain-tensor op returns immediately).",
    "DIVERGENT": "Either every rank raises the same error or every rank succeeds; ranks never desynchronise.",
    "EXCEPTION": "The op succeeds and matches the plain-tensor result (the plain-tensor program runs without error).",
    "CRASH": "No native crash; errors surface as Python exceptions.",
}


def write_env(bdir, key, launcher, slug):
    meta = json.load(open(os.path.join(dock.CACHE, f"image-{key}.json")))
    m = by_key(key)
    reqs = [r for r in meta["requirements"] if r and not r.startswith("#")]
    open(os.path.join(bdir, "requirements.txt"), "w").write("\n".join(reqs) + "\n")
    df = f"""# Pinned environment for this bug bundle (generated by distfuzz.repro).
# torch {meta["torch_version"]} CPU wheel, exact versions in requirements.txt (pip freeze of the image
# distfuzz.repro tested with, image id {meta["image_id"][:19]}).
FROM python:3.12-slim@sha256:2f17fc044b579bab302c2e8054d3a686e2cb9a83de48e70534b94cd8ebbe06a9
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 OMP_NUM_THREADS=1
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir {m["pip_extra"]} -r /tmp/requirements.txt \\
        --index-url {m["index"]} --extra-index-url https://pypi.org/simple
COPY repro.py /repro/repro.py
WORKDIR /repro
CMD {json.dumps([*launcher, "repro.py"])}
"""
    open(os.path.join(bdir, "Dockerfile"), "w").write(df)
    run = f"""#!/bin/sh
# One command: build the pinned image and run the repro with the limits distfuzz.repro used.
# Multi-rank PyTorch runs only inside the container.
set -e
cd "$(dirname "$0")"
docker build -q -t distfuzz-bundle:{slug} . >/dev/null
exec docker run --rm --network none --hostname repro --add-host repro:127.0.0.1 \\
  -e GLOO_SOCKET_IFNAME=lo --shm-size 512m --memory 3g --cpus 4 distfuzz-bundle:{slug} \\
  timeout -s KILL 300 {" ".join(launcher)} repro.py
"""
    p = os.path.join(bdir, "run.sh")
    open(p, "w").write(run)
    os.chmod(p, 0o755)
    return meta


def make_bundle(spec, log=print):
    """spec: dict(name, source, base='2.14.0', n=20, bisect_n=4, versions=None, known=[], queries=[],
    expected=None, minimize=True, bisect=True, world=None, notes='')"""
    name = spec["name"]
    bdir = os.path.join(BUNDLES, name)
    work = os.path.join(dock.CACHE, "work", name)
    shutil.rmtree(work, ignore_errors=True)
    os.makedirs(os.path.join(bdir, "logs"), exist_ok=True)
    t0 = time.time()
    finding = load(spec["source"], spec.get("world"))
    base = spec.get("base", "2.14.0")
    runner = pipeline.Runner(finding, work, timeout=spec.get("timeout", 150))
    data = dict(
        name=name,
        source=os.path.relpath(os.path.abspath(spec["source"].split("::")[0]))
        + ("::" + spec["source"].split("::")[1] if "::" in spec["source"] else ""),
        fuzzer=finding.fuzzer,
        fuzzer_sig=finding.fuzzer_sig,
        world=finding.world,
        launcher=finding.launcher,
        note=finding.note,
        notes=spec.get("notes", ""),
        base=base,
        created=time.strftime("%Y-%m-%d %H:%M"),
    )

    log(f"[{name}] reproduce on torch {base}")
    title, runs = pipeline.reproduce(runner, base, tries=3, target=spec.get("title"))
    open(os.path.join(bdir, "logs", "reproduce.txt"), "w").write(runs[-1]["out"] if runs else "")
    if title is None:
        data.update(
            status="not reproducible",
            title=None,
            first_runs=[{k: r[k] for k in ("rc", "title", "titles")} for r in runs],
        )
        json.dump(data, open(os.path.join(bdir, "bundle.json"), "w"), indent=1)
        log(f"[{name}] NOT reproduced on {base}")
        return data
    first = runs[-1]
    data.update(
        title=title,
        kind=first["kind"],
        alt_titles=[t for t in first["titles"] if t != title],
        evidence=first["evidence"],
    )
    log(f"[{name}] title: {title}")

    if spec.get("minimize", True):
        finding2, mstat = pipeline.minimize(finding, runner, base, title)
        if mstat.get("done"):
            chk, _ = pipeline.reproduce(runner, base, tries=3, target=title)
            mstat["verified"] = chk is not None
            if chk is None:  # minimized script lost the bug: keep the original
                runner.set_script(finding.script)
                mstat["kept_original"] = True
            else:
                finding = finding2
        data["minimize"] = mstat
        log(f"[{name}] minimize: {mstat}")
    if finding.rec is not None:
        json.dump(
            finding.rec,
            open(
                os.path.join(bdir, "program.min.json" if data.get("minimize", {}).get("done") else "program.json"), "w"
            ),
            indent=1,
        )
    open(os.path.join(bdir, "repro.py"), "w").write(finding.script)
    runner.f = finding
    runner.set_script(finding.script)

    log(f"[{name}] reliability x{spec.get('n', 20)} on torch {base}")
    rel = pipeline.reliability(runner, base, title, n=spec.get("n", 20))
    open(os.path.join(bdir, "logs", f"reliability-sample-{base}.txt"), "w").write(rel.pop("sample_bad") or "")
    so = rel.pop("sample_other")
    if so:
        open(os.path.join(bdir, "logs", f"reliability-other-{base}.txt"), "w").write(so)
    data["reliability"] = rel
    log(f"[{name}] reliability {rel['k']}/{rel['n']} {rel['verdict']} other={rel['other_outcomes']}")

    if spec.get("bisect", True):
        keys = spec.get("versions") or [m["key"] for m in matrix()]
        bis = pipeline.bisect_versions(runner, title, keys=keys, n=spec.get("bisect_n", 4), log=log)
        for r in bis["results"]:
            open(os.path.join(bdir, "logs", f"bisect-{r['version']}.txt"), "w").write(r.pop("sample"))
        bis["nightly"] = NIGHTLY_VERSION
        data["bisect"] = bis
        log(f"[{name}] first bad {bis['first_bad']} fixed in {bis['fixed_in']} {bis['note']}")

    env_key = base
    if data.get("bisect") and data["bisect"]["affected"]:
        rel_aff = [v for v in data["bisect"]["affected"] if v != "nightly"]
        env_key = (
            base if base in data["bisect"]["affected"] else (sorted(rel_aff, key=order)[-1] if rel_aff else "nightly")
        )
    meta = write_env(bdir, env_key, finding.launcher, slugify(name))
    data["env"] = dict(
        key=env_key,
        torch=meta["torch_version"],
        image_id=meta["image_id"],
        python="3.12 (python:3.12-slim@sha256:2f17fc04...)",
    )

    data["upstream"] = upstream.related(title, spec.get("queries", []), spec.get("known", []))
    data["expected"] = spec.get("expected") or EXPECTED_BY_KIND.get(data["kind"], "")
    data["status"] = "reproduced"
    data["elapsed_min"] = round((time.time() - t0) / 60, 1)
    json.dump(data, open(os.path.join(bdir, "bundle.json"), "w"), indent=1)
    render.write_reports(bdir, data)
    return data


def rerun_reliability(name, n=20, log=print):
    bdir = os.path.join(BUNDLES, name)
    data = json.load(open(os.path.join(bdir, "bundle.json")))
    f = Finding(
        source=data["source"],
        fuzzer=data["fuzzer"],
        fuzzer_sig=data["fuzzer_sig"],
        script=open(os.path.join(bdir, "repro.py")).read(),
        launcher=data["launcher"],
        world=data["world"],
    )
    runner = pipeline.Runner(f, os.path.join(dock.CACHE, "work", name))
    base = data["reliability"]["image"]
    rel = pipeline.reliability(runner, base, data["title"], n=n)
    open(os.path.join(bdir, "logs", f"reliability-sample-{base}.txt"), "w").write(rel.pop("sample_bad") or "")
    so = rel.pop("sample_other")
    if so:
        open(os.path.join(bdir, "logs", f"reliability-other-{base}.txt"), "w").write(so)
    data["reliability"] = rel
    json.dump(data, open(os.path.join(bdir, "bundle.json"), "w"), indent=1)
    log(
        f"[{name}] reliability {rel['k']}/{rel['n']} {rel['verdict']} "
        f"other={rel['other_outcomes']} excluded={rel['infra_excluded']}"
    )
